### ISSUE TITLE
Clearcase commands seem to do nothing, SCM view works

### ISSUE THREAD

**Issue by andreasWallner** [OpenNingia/vscode-clearcase#89] opened 2022-02-21 15:16 UTC
While the extension shows checkedout files etc. correctly in the SCM view, the commands from the command palette do not work. Neither do the commands from the context menu.

Example:
I have a folder with two files, one checked in, the other checked out:
```
(.env) 20 testcases/abc 1 % ct ls            
CMakeLists.txt@@/main/1                                  Rule: /main/LATEST
notmain.cpp@@/main/CHECKEDOUT from /main/3               Rule: CHECKEDOUT
```

I now open `notmain.cpp`, right click the text and select "Undo Checkout". Looking at the folder listing I can see that it is unchanged and `notmain.cpp` is still checked out.
While doing that the extension logs
```
clearcase, stdout: /var/vob/cli_n28/ric/vob/verification/testcases/reset_generation/notmain.cpp@@/main/CHECKEDOUT from /main/3              Rule: CHECKEDOUT

catcs
```
to the output window.

Alternatively if I try to check out `CMakeLists.txt` I see similar behavior: the status of the file does not change and
```
clearcase, stdout: /var/vob/cli_n28/ric/vob/verification/testcases/reset_generation/CMakeLists.txt@@/main/1                 Rule: /main/LATEST

catcs
```
is added to the log output. Nothing else happens (like e.g. a comment entry box which I'd have expected from skimming the sourcecode)

Is there any way to make the logging more verbose to see what is going on?

Environment Information:
* RHEL 7
* vscode-clearcase.useClearDlg=false (since we do not have cleardlg)
* Extension: v2.7.0
* VSCode 1.60.2

**Comment by jodymbrooks** [comment] 2022-03-10 18:34
I have a similar problem when undoing a checkout. I believe in my 2.7.0 version (on RHEL8), it may be because the configuration option for UncoKeepFile is not valid. It does not appear in package.json (there it appears it would be "uncoKeepFile"). 3.0.0 DOES have this parameter in package.json; however 3.0.0 is not available in the VS Marketplace yet to test this.

**Comment by fr43nk** [comment] 2022-07-13 04:48
Hi,
I'm not quite sure about the status of development of this extension. Maybe  @OpenNingia doesn't have enough time anymore  to maintain this. @jodymbrooks you said, with the unofficial version 3 the extension works again? In this, I added support for using the windows cleartool binary in an WSL environment. So perhaps this also helps working in a pure Linux host. @andreasWallner Are you able to build the extension from the latest code by your self or do you need support? I could provide you an vsix file if you want.

Best regards

**Comment by OpenNingia** [comment] 2022-07-13 08:01
Hi,

yes I currently don't have time to maintain this code and I also lost my main motivation since I'm not longer using ClearCase SCM at work. However if the problem is solvable by just publish the 3.0.0 version to the marketplace I can try ( my keys are probably expired by now).

**Comment by fr43nk** [comment] 2022-07-13 08:54
Hi,
thanks for publishing a new version. One question remains: What is your plan regarding this extension? Should someone else be the maintainer of it?

**Comment by OpenNingia** [comment] 2022-07-14 10:26
@fr43nk  I've no future plan for this extension. If you (or someone else) are stepping up to became the new maintainer(s) I think that we could arrange it.

**Comment by OpenNingia** [comment] 2022-07-15 12:28
I'll close this issue since it seems ok now, let's move this discussion somewhere else

**Closed by OpenNingia** 2022-07-15 12:28 UTC

**Comment by andreasWallner** [comment] 2022-08-09 12:20
@fr43nk @OpenNingia thanks for the update, I'll try the new release - in any case many thanks for the work you already invested!

**Comment by jodymbrooks** [comment] 2022-08-09 13:20
For the record, this release DID fix the issues I was seeing. Thanks much!
